name: Use Repository Secret

on:
  push:
    branches: [main]

jobs:
  reveal-secret:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Print Secret Securely
        run: echo "API key is ${{ secrets.API_KEY }}"
